// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BindShortcutField: typeof import('./src/components/form/BindShortcutField.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WidgetBaseDialog: typeof import('./src/components/dialog/WidgetBaseDialog.vue')['default']
    WidgetCheckboxField: typeof import('./src/components/form/WidgetCheckboxField.vue')['default']
    WidgetColorField: typeof import('./src/components/form/WidgetColorField.vue')['default']
    WidgetDialogTitleBar: typeof import('./src/components/dialog/WidgetDialogTitleBar.vue')['default']
    WidgetEditDialog: typeof import('./src/components/dialog/WidgetEditDialog.vue')['default']
    WidgetFitBox: typeof import('./src/components/WidgetFitBox.vue')['default']
    WidgetSliderField: typeof import('./src/components/form/WidgetSliderField.vue')['default']
    WidgetTimeRangeField: typeof import('./src/components/form/WidgetTimeRangeField.vue')['default']
  }
}
